<?php

namespace ContainerW6zvCYT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFakturowniaReportManagerService extends Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Codevenom\FakturowniaBundle\Report\FakturowniaReportManager' shared autowired service.
     *
     * @return \Codevenom\FakturowniaBundle\Report\FakturowniaReportManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Report/FakturowniaReportManager.php';

        return $container->services['Codevenom\\FakturowniaBundle\\Report\\FakturowniaReportManager'] = new \Codevenom\FakturowniaBundle\Report\FakturowniaReportManager();
    }
}
