<?php

namespace ContainerW6zvCYT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoicePayloadMapperService extends Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Codevenom\FakturowniaBundle\Invoice\Mapper\InvoicePayloadMapper' shared autowired service.
     *
     * @return \Codevenom\FakturowniaBundle\Invoice\Mapper\InvoicePayloadMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Mapper/AbstractPayloadMapper.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Mapper/PayloadMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Invoice/Mapper/InvoicePayloadMapper.php';

        return $container->services['Codevenom\\FakturowniaBundle\\Invoice\\Mapper\\InvoicePayloadMapper'] = new \Codevenom\FakturowniaBundle\Invoice\Mapper\InvoicePayloadMapper(($container->privates['serializer'] ?? self::getSerializerService($container)));
    }
}
