services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Codevenom\FakturowniaBundle\:
    resource: '../../src/*'
    exclude:
      - '../../src/DependencyInjection/'
      - '../../src/CodevenomFakturowniaBundle.php'
      - '../../src/Invoice/Model/'
      - '../../src/Invoice/Enum/'
      - '../../src/Invoice/Factory/'
      - '../../src/Report/Model/'
      - '../../src/Report/Factory/'
      - '../../src/Exception/'
      - '../../src/Shared/Mapper/'   # interfaces only, not services

  # Concrete client with params
  Codevenom\FakturowniaBundle\Client\InvoiceClient:
    arguments:
      $baseUrl: '%codevenom_fakturownia.base_url%'
      $apiToken: '%codevenom_fakturownia.api_token%'
      $sellerName: '%codevenom_fakturownia.seller_name%'
      $timeout: '%codevenom_fakturownia.timeout%'


  # Interfaces aliases (the important part for clean usage/tests)
  Codevenom\FakturowniaBundle\Client\FakturowniaClientInterface:
    alias: Codevenom\FakturowniaBundle\Client\InvoiceClient

  Codevenom\FakturowniaBundle\Invoice\InvoiceManagerInterface:
    alias: Codevenom\FakturowniaBundle\Invoice\InvoiceManager