<?php

namespace ContainerULK8xPM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFakturowniaFacadeService extends Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Codevenom\FakturowniaBundle\Facade\FakturowniaFacade' shared autowired service.
     *
     * @return \Codevenom\FakturowniaBundle\Facade\FakturowniaFacade
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Facade/FakturowniaFacade.php';

        return $container->services['Codevenom\\FakturowniaBundle\\Facade\\FakturowniaFacade'] = new \Codevenom\FakturowniaBundle\Facade\FakturowniaFacade();
    }
}
