<?php

namespace ContainerULK8xPM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceManagerService extends Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Codevenom\FakturowniaBundle\Invoice\InvoiceManager' shared autowired service.
     *
     * @return \Codevenom\FakturowniaBundle\Invoice\InvoiceManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Invoice/InvoiceManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Invoice/InvoiceManager.php';

        return $container->services['Codevenom\\FakturowniaBundle\\Invoice\\InvoiceManager'] = new \Codevenom\FakturowniaBundle\Invoice\InvoiceManager(($container->services['Codevenom\\FakturowniaBundle\\Invoice\\Service\\InvoiceService'] ?? $container->load('getInvoiceServiceService')));
    }
}
