<?php

namespace ContainerXRgqq2N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceClientService extends Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Codevenom\FakturowniaBundle\Client\InvoiceClient' shared autowired service.
     *
     * @return \Codevenom\FakturowniaBundle\Client\InvoiceClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Client/AbstractFakturowniaClient.php';
        include_once \dirname(__DIR__, 4).'/src/Client/FakturowniaClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Client/InvoiceClient.php';

        return $container->services['Codevenom\\FakturowniaBundle\\Client\\InvoiceClient'] = new \Codevenom\FakturowniaBundle\Client\InvoiceClient($container->getEnv('FAKTUROWNIA_BASE_URL'), $container->getEnv('FAKTUROWNIA_API_TOKEN'), 10, $container->getEnv('default::FAKTUROWNIA_SELLER_NAME'), ($container->services['Codevenom\\FakturowniaBundle\\Invoice\\Mapper\\InvoicePayloadMapper'] ?? $container->load('getInvoicePayloadMapperService')), ($container->services['Codevenom\\FakturowniaBundle\\Invoice\\Mapper\\CreateInvoicePayloadMapper'] ?? $container->load('getCreateInvoicePayloadMapperService')));
    }
}
