services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Codevenom\FakturowniaBundle\Application\:
    resource: '../src/Application/'
    exclude:
      - '../src/Application/Command/'
      - '../src/Application/Dto/'
      - '../src/Application/Query/'

  # Register only folders that contain container-managed services:
  Codevenom\FakturowniaBundle\Infrastructure\FakturowniaApi\Http\:
    resource: '../src/Infrastructure/FakturowniaApi/Http/'

  Codevenom\FakturowniaBundle\Infrastructure\FakturowniaApi\Adapter\:
    resource: '../src/Infrastructure/FakturowniaApi/Adapter/'

  Codevenom\FakturowniaBundle\Infrastructure\FakturowniaApi\Mapper\:
    resource: '../src/Infrastructure/FakturowniaApi/Mapper/'

  Codevenom\FakturowniaBundle\Infrastructure\FakturowniaApi\Event\:
    resource: '../src/Infrastructure/FakturowniaApi/Event/'

  Codevenom\FakturowniaBundle\Infrastructure\FakturowniaApi\Http\FakturowniaClient:
    arguments:
      $baseUrl: '%codevenom_fakturownia.base_url%'
      $sellerName: '%codevenom_fakturownia.seller_name%'
      $apiToken: '%codevenom_fakturownia.api_token%'
      $timeout: '%codevenom_fakturownia.timeout%'

  Codevenom\FakturowniaBundle\Domain\Contract\Port\FakturowniaGatewayInterface:
    alias: Codevenom\FakturowniaBundle\Infrastructure\FakturowniaApi\Adapter\FakturowniaGatewayAdapter

  Codevenom\FakturowniaBundle\Domain\Contract\FakturowniaInterface:
    alias: Codevenom\FakturowniaBundle\Application\FakturowniaService