<?php

namespace ContainerFOrgSjS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceServiceService extends Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Codevenom\FakturowniaBundle\Invoice\Service\InvoiceService' shared autowired service.
     *
     * @return \Codevenom\FakturowniaBundle\Invoice\Service\InvoiceService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Invoice/Service/InvoiceService.php';

        return $container->services['Codevenom\\FakturowniaBundle\\Invoice\\Service\\InvoiceService'] = new \Codevenom\FakturowniaBundle\Invoice\Service\InvoiceService(($container->services['Codevenom\\FakturowniaBundle\\Client\\InvoiceClient'] ?? $container->load('getInvoiceClientService')));
    }
}
