<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFOrgSjS\Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFOrgSjS/Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFOrgSjS.legacy');

    return;
}

if (!\class_exists(Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFOrgSjS\Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, false);
}

return new \ContainerFOrgSjS\Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer([
    'container.build_hash' => 'FOrgSjS',
    'container.build_id' => 'f145c903',
    'container.build_time' => 1776446594,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFOrgSjS');
