<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW6zvCYT\Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW6zvCYT/Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerW6zvCYT.legacy');

    return;
}

if (!\class_exists(Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerW6zvCYT\Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer::class, false);
}

return new \ContainerW6zvCYT\Codevenom_FakturowniaBundle_Tests_App_TestKernelTestDebugContainer([
    'container.build_hash' => 'W6zvCYT',
    'container.build_id' => '1f3cbd82',
    'container.build_time' => 1776441072,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW6zvCYT');
